/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AreaSelect: typeof import('./src/components/area/AreaSelect.vue')['default']
    AreaSelectAsync: typeof import('./src/components/area/AreaSelectAsync.vue')['default']
    BarSimple: typeof import('./src/components/echartsCom/BarSimple.vue')['default']
    DateSelect: typeof import('./src/components/date/DateSelect.vue')['default']
    ImagePreview: typeof import('./src/components/file/ImagePreview.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    ModelSelector: typeof import('./src/components/select/ModelSelector.vue')['default']
    PieBorderRadius: typeof import('./src/components/echartsCom/PieBorderRadius.vue')['default']
    RoleFilter: typeof import('./src/components/role/roleFilter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDivider: typeof import('vant/es')['Divider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanSearch: typeof import('vant/es')['Search']
    WecomUserSelect: typeof import('./src/components/wecomUser/wecomUserSelect.vue')['default']
  }
}
