/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlgoConfigEditor: typeof import('./src/components/quiz/AlgoConfigEditor.vue')['default']
    AnimatedBackground: typeof import('./src/components/background/AnimatedBackground.vue')['default']
    EditModal: typeof import('./src/components/sys/dept/EditModal.vue')['default']
    ImageUploadList: typeof import('./src/components/quiz/ImageUploadList.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    OutcomeEditor: typeof import('./src/components/quiz/OutcomeEditor.vue')['default']
    PrivacyPolicy: typeof import('./src/components/sys/auth/PrivacyPolicy.vue')['default']
    QuestionEditor: typeof import('./src/components/quiz/QuestionEditor.vue')['default']
    QuizForm: typeof import('./src/components/quiz/QuizForm.vue')['default']
    QuizStats: typeof import('./src/components/quiz/QuizStats.vue')['default']
    ResetSelfPassword: typeof import('./src/components/sys/auth/ResetSelfPassword.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectAssignModal: typeof import('./src/components/sys/permission/SelectAssignModal.vue')['default']
    SelectModal: typeof import('./src/components/sys/dept/SelectModal.vue')['default']
    SelectOneModal: typeof import('./src/components/sys/dept/SelectOneModal.vue')['default']
    SideBar: typeof import('./src/components/sys/sideBar/SideBar.vue')['default']
    SidebarItem: typeof import('./src/components/sys/sideBar/SidebarItem.vue')['default']
    UserAgreement: typeof import('./src/components/sys/auth/UserAgreement.vue')['default']
    ValidateCaptchaModal: typeof import('./src/components/sys/captcha/ValidateCaptchaModal.vue')['default']
  }
}
